service: serverless-ruby-simple-http-endpoint
frameworkVersion: "3"

provider:
  name: aws
  runtime: ruby3.2

functions:
  current_time:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
